server:
  port: 8200
#指定应用的名称
spring:
  application:
    name: consumer-user

eureka:
  instance:
    #注册服务的时候使用服务的ip地址
    prefer-ip-address: true
  client:
    #指定注册中心的地址
    service-url:
      defaultZone: http://localhost:8761/eureka/