spring:
  datasource:
    url: jdbc:mysql://192.168.25.157:3306/jpa
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true